Repository status-im/nimbus-eth2, pull requests merged in 2019-12, with the labels that each got.

#621 Fix instr when cloning from scratch
  Makefile
  README.md
Labels: work in progress

#617 render get_beacon_proposer_index(...) return value an option and remove overly aggressive assertion formerly causing crashes when missing validators
  beacon_chain/beacon_node.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/state_transition_block.nim
  beacon_chain/spec/validator.nim
  tests/mocking/mock_blocks.nim
  tests/testblockutil.nim
Labels: merge ready

#624 measure/find slow tests
  tests/all_tests.nim
  tests/official/all_fixtures_require_ssz.nim
  tests/official/test_fixture_bls.nim
  tests/official/test_fixture_const_sanity_check.nim
  tests/official/test_fixture_operations_attestations.nim
  tests/official/test_fixture_operations_attester_slashings.nim
  tests/official/test_fixture_operations_block_header.nim
  tests/official/test_fixture_operations_deposits.nim
  tests/official/test_fixture_operations_proposer_slashings.nim
  tests/official/test_fixture_operations_voluntary_exit.nim
  tests/official/test_fixture_sanity_blocks.nim
  tests/official/test_fixture_sanity_slots.nim
  tests/official/test_fixture_shuffling.nim
  tests/official/test_fixture_ssz_consensus_objects.nim
  tests/official/test_fixture_ssz_generic_types.nim
  tests/official/test_fixture_state_transition_epoch.nim
  tests/spec_block_processing/test_genesis.nim
  tests/spec_block_processing/test_process_attestation.nim
  tests/spec_block_processing/test_process_deposits.nim
  tests/spec_epoch_processing/test_process_justification_and_finalization.nim
  tests/test_attestation_pool.nim
  tests/test_beacon_chain_db.nim
  tests/test_beacon_node.nim
  tests/test_beaconstate.nim
  tests/test_block_pool.nim
  tests/test_helpers.nim
  tests/test_interop.nim
  tests/test_peer_pool.nim
  tests/test_ssz.nim
  tests/test_state_transition.nim
  tests/test_sync_protocol.nim
  tests/test_zero_signature.nim
  tests/testutil.nim
Labels: merge ready, performance, test suite

#625 connect_to_testnet.nims: default to "n" on the interactive prompt
  scripts/connect_to_testnet.nims
Labels: polish

#627 switch debug to notice and add some contextual information
  beacon_chain/beacon_node.nim
Labels: merge ready

#628 Misc cleanups (including warning removal)
  beacon_chain.nimble
  beacon_chain/libp2p_daemon_backend.nim
  beacon_chain/request_manager.nim
Labels: merge ready

#630 Reduce CI times by 2+ minutes keeping all real tests
  beacon_chain/ssz.nim
  tests/all_tests.nim
  tests/test_peer_connection.nim
Labels: merge ready

#643 move attesting up from halfway to one third of the way through slots
  beacon_chain/beacon_node.nim
  beacon_chain/time.nim
Labels: merge ready

#656 fix genesis interop by fixing deposit signature handling
  beacon_chain.nimble
  beacon_chain/interop.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/datatypes.nim
  tests/all_tests.nim
  tests/mocking/mock_deposits.nim
  tests/test_interop.nim
  tests/testblockutil.nim
Labels: merge ready

#641 Nbench - Flexible benchmarking of Nimbus internals
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/state_transition_block.nim
  beacon_chain/spec/state_transition_epoch.nim
  beacon_chain/state_transition.nim
  nbench/README.md
  nbench/bench_lab.nim
  nbench/foo.nim
  nbench/nbench.nim
  nbench/nbench.nim.cfg
  nbench/nbench_official_fixtures.nim
  nbench/platforms/x86.nim
  nbench/reports.nim
  nbench/scenarios.nim
  tests/official/test_fixture_operations_attester_slashings.nim
Labels: merge ready
