Repository status-im/nimbus-eth2, pull requests merged in 2020-07, with the labels that each got.

#1263 Move the nimbus book in a subfolder to allow for more books
  .gitignore
  Makefile
  docs/the_nimbus_book/.gitignore
  docs/the_nimbus_book/book.toml
  docs/the_nimbus_book/src/SUMMARY.md
  docs/the_nimbus_book/src/advanced.md
  docs/the_nimbus_book/src/api.md
  docs/the_nimbus_book/src/cli.md
  docs/the_nimbus_book/src/contribute.md
  docs/the_nimbus_book/src/faq.md
  docs/the_nimbus_book/src/img/beacon_node_example.PNG
  docs/the_nimbus_book/src/img/connect_testnet.PNG
  docs/the_nimbus_book/src/img/deposit_sent.PNG
  docs/the_nimbus_book/src/img/enter_private_key.PNG
  docs/the_nimbus_book/src/img/export_pkey.PNG
  docs/the_nimbus_book/src/img/success.PNG
  docs/the_nimbus_book/src/install.md
  docs/the_nimbus_book/src/intro.md
  docs/the_nimbus_book/src/validator.md
Labels: merge ready

#1275 adopt Result[void, string] in place of some bool return signatures
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/state_transition_block.nim
  nbench/scenarios.nim
  nfuzz/libnfuzz.nim
  tests/official/test_fixture_operations_attestations.nim
  tests/official/test_fixture_operations_attester_slashings.nim
  tests/official/test_fixture_operations_block_header.nim
  tests/official/test_fixture_operations_deposits.nim
  tests/official/test_fixture_operations_proposer_slashings.nim
  tests/official/test_fixture_operations_voluntary_exit.nim
  tests/spec_block_processing/test_process_attestation.nim
  tests/spec_block_processing/test_process_deposits.nim
Labels: merge ready

#1280 [WIP] The Auditors Handbook
  Makefile
  docs/the_auditors_handbook/.gitignore
  docs/the_auditors_handbook/book.toml
  docs/the_auditors_handbook/src/01_introduction.md
  docs/the_auditors_handbook/src/02.1.1_operators_bit_manipulation.md
  docs/the_auditors_handbook/src/02.1.2_pointer_manipulation.md
  docs/the_auditors_handbook/src/02.1.3_emitting_raw_C_assembly_code.md
  docs/the_auditors_handbook/src/02.1.4_closure_iterators.md
  docs/the_auditors_handbook/src/02.10_Nim_FAQ.md
  docs/the_auditors_handbook/src/02.1_nim_routines_proc_func_templates_macros.md
  docs/the_auditors_handbook/src/02.2.1_builtin_types.md
  docs/the_auditors_handbook/src/02.2.2_casting_and_low_level_memory_representation.md
  docs/the_auditors_handbook/src/02.2.3_memory_management_gc.md
  docs/the_auditors_handbook/src/02.2.4_generics_types_static_types.md
  docs/the_auditors_handbook/src/02.2.5_arrays_openarrays_strings_cstring.md
  docs/the_auditors_handbook/src/02.2.6_runtime_types_variants_oop.md
  docs/the_auditors_handbook/src/02.2.7_compiletime_evaluation.md
  docs/the_auditors_handbook/src/02.2_stack_ref_ptr_types.md
  docs/the_auditors_handbook/src/02.3_correctness_distinct_mutability_effects_exceptions.md
  docs/the_auditors_handbook/src/02.4_debugging_Nim_sanitizers_fuzzers.md
  docs/the_auditors_handbook/src/02.5_foreign_lang_to_from_interop.md
  docs/the_auditors_handbook/src/02.8_Nim_threat_model.md
  docs/the_auditors_handbook/src/02.9_Nim_stdlib_use_in_nimbus.md
  docs/the_auditors_handbook/src/02_the_Nim_programming_language.md
  docs/the_auditors_handbook/src/03.2_build_system_and_dependencies.md
  docs/the_auditors_handbook/src/03.5_the_threat_model.md
  docs/the_auditors_handbook/src/03_nbc_nimbus_beacon_chain.md
  docs/the_auditors_handbook/src/04_serialization.md
  docs/the_auditors_handbook/src/05_async_with_chronos.md
  docs/the_auditors_handbook/src/06_cryptography_and_rng.md
  docs/the_auditors_handbook/src/07_nim-eth.md
  docs/the_auditors_handbook/src/SUMMARY.md
Labels: :book: documentation, security, work in progress

#1285 Fix PeerPool issue with number peers overflow maxPeers setting.
  beacon_chain/peer_pool.nim
  tests/test_peer_pool.nim
Labels: merge ready

#1279 Forward sync start at finalized epoch
  beacon_chain/sync_manager.nim
Labels: merge ready

#1287 allow 50k validators on block_sim
  beacon_chain/spec/state_transition_epoch.nim
Labels: merge ready

#1238 Dual headed fork choice [Revolution]
  AllTests-mainnet.md
  beacon_chain/attestation_pool.nim
  beacon_chain/beacon_node.nim
  beacon_chain/beacon_node_common.nim
  beacon_chain/beacon_node_types.nim
  beacon_chain/block_pool.nim
  beacon_chain/block_pools/block_pools_types.nim
  beacon_chain/block_pools/candidate_chains.nim
  beacon_chain/block_pools/clearance.nim
  beacon_chain/fork_choice/fork_choice.nim
  beacon_chain/fork_choice/proto_array.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/validator_duties.nim
  research/block_sim.nim
  tests/test_attestation_pool.nim
  tests/test_block_pool.nim
Labels: work in progress

#1292 update most remaining non-fork-choice spec refs, updating code where necessary
  AllTests-mainnet.md
  beacon_chain/attestation_aggregation.nim
  beacon_chain/attestation_pool.nim
  beacon_chain/block_pools/candidate_chains.nim
  beacon_chain/inspector.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/network.nim
  beacon_chain/spec/state_transition.nim
  beacon_chain/spec/state_transition_epoch.nim
  beacon_chain/spec/state_transition_helpers.nim
  tests/mocking/mock_genesis.nim
Labels: merge ready

#1295 Fix syncman topics log lines.
  beacon_chain/sync_manager.nim
Labels: merge ready

#1294 Improve block_sim speed with 50k+ validators
  beacon_chain.nimble
  beacon_chain/attestation_pool.nim
  beacon_chain/beacon_node.nim
  beacon_chain/spec/datatypes.nim
  beacon_chain/spec/state_transition_epoch.nim
  beacon_chain/spec/validator.nim
  beacon_chain/validator_api.nim
Labels: merge ready

#1299 synchronize test result summary with make test results
  AllTests-mainnet.md
  beacon_chain/eth2_discovery.nim
Labels: merge ready

#1325 fix over/underflow in proposerslashing processing
  beacon_chain/spec/state_transition_block.nim
Labels: merge ready

#1351 drop get_attesting_indices() from 15% to 1% of block_sim at 100k validators
  beacon_chain/block_pools/candidate_chains.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/crypto.nim
  beacon_chain/spec/state_transition_helpers.nim
Labels: merge ready

#1346 Implement dynamic subscribe/unsubscribe infrastructure
  beacon_chain/attestation_aggregation.nim
  beacon_chain/spec/network.nim
  beacon_chain/spec/validator.nim
  beacon_chain/validator_api.nim
  beacon_chain/validator_duties.nim
  ncli/ncli_db.nim
  research/state_sim.nim
  tests/spec_epoch_processing/justification_finalization_helpers.nim
Labels: merge ready

#1372 Stopgap don't print private key in shortlog
  beacon_chain/spec/crypto.nim
Labels: security

#1375 Prefer converting int` to uint64 and switch foo.len.uint64 to .len64
  beacon_chain/attestation_aggregation.nim
  beacon_chain/attestation_pool.nim
  beacon_chain/block_pool.nim
  beacon_chain/eth2_network.nim
  beacon_chain/mainchain_monitor.nim
  beacon_chain/spec/beaconstate.nim
  beacon_chain/spec/datatypes.nim
  beacon_chain/spec/helpers.nim
  beacon_chain/spec/state_transition.nim
  beacon_chain/spec/state_transition_block.nim
  beacon_chain/spec/state_transition_epoch.nim
  beacon_chain/spec/validator.nim
  beacon_chain/validator_api.nim
  nfuzz/libnfuzz.nim
  research/state_sim.nim
  tests/mocking/mock_deposits.nim
  tests/spec_block_processing/test_process_attestation.nim
  tests/spec_block_processing/test_process_deposits.nim
  tests/spec_epoch_processing/test_process_justification_and_finalization.nim
  tests/test_beaconstate.nim
  tests/test_ssz.nim
  tests/test_state_transition.nim
  tests/testblockutil.nim
Labels: merge ready

#1361 Implement log tracing of attestation send and receive messages.
  beacon_chain/logtrace.nim
Labels: merge ready

#1386 verifyFinalization checks for justification being consistent with finalization
  beacon_chain/spec/state_transition_epoch.nim
Labels: merge ready

#1393 combine ncli_hash_tree_root and ncli_pretty into ncli_ssz
  Makefile
  nbench/scenarios.nim
  ncli/ncli.nim
  ncli/ncli_hash_tree_root.nim
  ncli/ncli_pretty.nim
  ncli/ncli_transition.nim
Labels: merge ready
